name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Hi @${{ github.event.issue.user.login }} :wave:, you have not yet submitted your post-event and/or expense report. Kindly use the [Post Event Template](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md) or read the [Expenses Guidelines](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md) and submit your report so that we can review and close this issue. Thank you!'
        stale-issue-label: 'no-post-event-report'
        days-before-issue-stale: 30
        days-before-issue-close: -1
